version: "3.9"
services:
  db:
    image: postgres:15-alpine
    command: postgres -c fsync=off -c synchronous_commit=off -c full_page_writes=off -c random_page_cost=1.0
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: api
      PGDATA: /var/lib/postgresql/data
    tmpfs: /var/lib/postgresql/data
    ports:
      - '5432:5432'
    expose:
      - 5432
    restart: unless-stopped
  db-migrator:
    build: .
    command: migrate -d api -i
    environment:
      FLYWAY_URL: jdbc:postgresql://db:5432/api
      FLYWAY_USER: postgres
      FLYWAY_PASSWORD: password123
    restart: unless-stopped
    depends_on:
      - db
    links:
      - db:db