CREATE TABLE IF NOT EXISTS "Bank" (
    "id" UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    "name" VARCHAR UNIQUE NOT NULL,
    "logoUrl" VARCHAR NOT NULL,
    "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TRIGGER PREVENT_BANK_DELETION
BEFORE DELETE ON "Bank"
FOR EACH ROW
EXECUTE PROCEDURE prevent_operation();
